Finally realized parse function
andriidem308/hillel_course pull request #3
Opened 2021-03-16 09:12 UTC by andriidem308

2021-03-16 09:17 UTC, romanitalian commented on parse.py
> +            if '=' in o: dct[o.split('=')[0]] = o.split('=')[1]
Переназначается переменная: o
здесь `for o in options:` и здесь `o: dct[o.split('=')[0]]`

2021-03-16 09:17 UTC, romanitalian commented on parse.py
> +            if '=' in o: dct[o.split('=')[0]] = o.split('=')[1]
PEP 8: E701

2021-03-16 09:17 UTC, romanitalian requested changes

2021-03-16 09:17 UTC, romanitalian commented on parse.py
> +    assert parse('http://example.com/?name=Dima') == {'name': 'Dima'}
В конце файла - пустая строка.

2021-03-16 09:18 UTC, romanitalian commented
Не нужно пересоздавать ПР. Просто делаешь правки в ветке. И потом эти изменения в ветку закидываешь (git push origin branch_name). И эти изменения появятся в ПР.

2021-03-16 09:25 UTC, andriidem308 commented
> Не нужно пересоздавать ПР. Просто делаешь правки в ветке. И потом эти изменения в ветку закидываешь (git push origin branch_name). И эти изменения появятся в ПР.

Да, знаю, вылетело из головы. Давно не делал ПР.

2021-03-16 09:29 UTC, andriidem308 commented on parse.py
> +            if '=' in o: dct[o.split('=')[0]] = o.split('=')[1]
А каким образом она переназначается???

2021-03-16 09:29 UTC, andriidem308 commented on parse.py
> +    assert parse('http://example.com/?name=Dima') == {'name': 'Dima'}
У меня IDE всегда говорит оставлять пустую строку в конце, поэтому я так делаю в 90% случаях

2021-03-16 09:31 UTC, andriidem308 commented on parse.py
> +            if '=' in o: dct[o.split('=')[0]] = o.split('=')[1]
Ааа, вы имеете в виду переопределить её в o.split('=')

2021-03-16 09:35 UTC, andriidem308 commented on parse.py
> +    assert parse('http://example.com/?name=Dima') == {'name': 'Dima'}
Всё, извините? Я ещё видимо не проснулся.. У меня она есть локально, не знаю почему её не добавило :/

2021-03-18 16:24 UTC, merged

2021-03-18 19:48 UTC, romanitalian commented on parse.py
> +    assert parse('http://example.com/?name=Dima') == {'name': 'Dima'}
Супер.

2021-03-18 19:48 UTC, romanitalian commented on parse.py
> +            if '=' in o: dct[o.split('=')[0]] = o.split('=')[1]
можно и так, а можно o: переименовать в другую. Это не критично.
Если в PyCharm делать - она подскажет.